'use client';

import React, { useState, useEffect } from 'react';
import axiosInstance from '@/lib/axios';
import ReactMarkdown from 'react-markdown';
import { Bot, Calendar, Sparkles, Loader2, Inbox, Clock } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import toast from 'react-hot-toast';

export default function AIBriefingsPage() {
    const [briefings, setBriefings] = useState([]);
    const [isLoading, setIsLoading] = useState(true);

    useEffect(() => {
        fetchBriefings();
    }, []);

    const fetchBriefings = async () => {
        try {
            const res = await axiosInstance.get('/ai/briefings');
            if (res.data.success) {
                setBriefings(res.data.briefings);
            }
        } catch (error) {
            toast.error("Failed to load AI briefings");
        } finally {
            setIsLoading(false);
        }
    };

    const formatDate = (dateString) => {
        const date = new Date(dateString);
        return {
            day: date.toLocaleDateString('en-IN', { weekday: 'long' }),
            full: date.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }),
            time: date.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })
        };
    };

    return (
        <div className="min-h-[calc(100vh-88px)] bg-[#F4EEFD] rounded-[24px] p-6 lg:p-8 -m-4 lg:-m-6 font-sans">
            
            {/* Header */}
            <div className="flex items-center gap-4 mb-8">
                <div className="w-14 h-14 rounded-2xl bg-white border border-[#E9DFFC] shadow-sm flex items-center justify-center">
                    <Bot size={28} className="text-[#6B4DF1]" />
                </div>
                <div>
                    <div className="flex items-center gap-2">
                        <h1 className="text-[24px] font-black text-[#27225B] tracking-tight m-0">AI Daily Briefings</h1>
                        <Sparkles size={20} className="text-[#F59E0B]" />
                    </div>
                    <p className="text-[#7D8DA6] text-[14px] font-medium mt-1 mb-0">Your proactive system health reports and insights generated by the AI Cron Agent.</p>
                </div>
            </div>

            {/* Content */}
            {isLoading ? (
                <div className="flex flex-col items-center justify-center h-[400px]">
                    <Loader2 size={40} className="text-[#6B4DF1] animate-spin mb-4" />
                    <p className="text-[#7D8DA6] font-bold tracking-widest uppercase text-[12px]">Decrypting Reports...</p>
                </div>
            ) : briefings.length === 0 ? (
                <div className="bg-white rounded-[20px] border border-[#E9DFFC] p-12 flex flex-col items-center justify-center text-center shadow-sm">
                    <div className="w-20 h-20 bg-[#F4F0FD] rounded-full flex items-center justify-center mb-6">
                        <Inbox size={32} className="text-[#6B4DF1]" />
                    </div>
                    <h3 className="text-[#27225B] text-[18px] font-black mb-2">No Briefings Yet</h3>
                    <p className="text-[#7D8DA6] text-[14px] max-w-md">The AI Agent will generate its first report according to the scheduled cron job. Check back later!</p>
                </div>
            ) : (
                <div className="grid grid-cols-1 gap-6 max-w-4xl">
                    <AnimatePresence>
                        {briefings.map((briefing, index) => {
                            const dateObj = formatDate(briefing.createdAt);
                            
                            return (
                                <motion.div 
                                    key={briefing._id}
                                    initial={{ opacity: 0, y: 20 }}
                                    animate={{ opacity: 1, y: 0 }}
                                    transition={{ delay: index * 0.1 }}
                                    className="bg-white border border-[#E9DFFC] rounded-[20px] shadow-sm overflow-hidden flex flex-col md:flex-row"
                                >
                                    {/* Date Sidebar */}
                                    <div className="bg-[#F9F7FC] md:w-48 p-6 border-b md:border-b-0 md:border-r border-[#E9DFFC] flex flex-col justify-center">
                                        <div className="flex items-center gap-2 text-[#6B4DF1] mb-2">
                                            <Calendar size={16} />
                                            <span className="text-[12px] font-black uppercase tracking-wider">{dateObj.day}</span>
                                        </div>
                                        <div className="text-[22px] font-black text-[#27225B] leading-tight">{dateObj.full}</div>
                                        <div className="flex items-center gap-1.5 text-[#A0ABC0] mt-3">
                                            <Clock size={14} />
                                            <span className="text-[13px] font-bold">{dateObj.time}</span>
                                        </div>
                                    </div>

                                    {/* Briefing Content */}
                                    <div className="p-6 md:p-8 flex-1">
                                        <div className="text-[14px] text-[#4A5568] leading-relaxed break-words">
                                            <ReactMarkdown
                                                components={{
                                                    p: ({node, ...props}) => <p className="mb-3 last:mb-0" {...props} />,
                                                    strong: ({node, ...props}) => <strong className="font-black text-[#27225B]" {...props} />,
                                                    ul: ({node, ...props}) => <ul className="list-disc pl-5 mb-3 space-y-1 marker:text-[#6B4DF1]" {...props} />,
                                                    li: ({node, ...props}) => <li className="" {...props} />,
                                                }}
                                            >
                                                {briefing.message}
                                            </ReactMarkdown>
                                        </div>
                                    </div>
                                </motion.div>
                            );
                        })}
                    </AnimatePresence>
                </div>
            )}
        </div>
    );
}